### ISSUE TITLE
[bug] auto-start placement results in incorrect starting position

### ISSUE THREAD

**Issue by mattrothenberg** [popperjs/popper-core#1134] opened 2020-06-18 03:01 UTC
### CodeSandbox demo
https://codesandbox.io/s/amazing-sound-zepwt?file=/src/App.js

### Steps to reproduce the problem

1. Set the placement to `auto-start` or `auto-end`
2. Enable the `flip` modifier, specifying `bottom-start` and `bottom-end` as `allowedAutoPlacements`
3. Observe that the popper **does not** choose the bottom-start position, even when there's ample room to do so.

### What is the expected behavior?

If I'm using `auto-start`, and there's room in the viewport for the popper to go below its reference element, the popper should go below (not above) its reference element.

### What went wrong?

The popper unpredictably goes above its reference element.

### Any other comments?

Note how, in that Codesandbox link, if you change the placement to `bottom` (instead of `auto-start`), the popper is positioned correctly.

**Demo illustrating issue with auto-start**
![Kapture 2020-06-17 at 21 55 01](https://user-images.githubusercontent.com/5148596/84973140-f903da00-b0e5-11ea-8521-c49f68b0f273.gif)

**Comment by atomiks** [comment] 2020-06-18 06:05
That's how `auto` works. It chooses the side with most space. If you want the desired behavior you can't use `auto`

**Comment by diondiondion** [comment] 2020-06-25 09:15
> That's how `auto` works. It chooses the side with most space. If you want the desired behavior you can't use `auto`

But when only `bottom-start` and `bottom-end` are set as `allowedAutoPlacements`, shouldn't only those be chosen even if there's more space in another direction?

**Comment by mattrothenberg** [comment] 2020-06-25 11:28
@diondiondion That was exactly my thinking, too. I was definitely surprised to read that auto "chooses the side with most space" **irrespective** of what allowed auto placements were specified.

**Comment by atomiks** [comment] 2020-06-25 11:51
> But when only bottom-start and bottom-end are set as allowedAutoPlacements, shouldn't only those be chosen even if there's more space in another direction?

Hmm, I can't reproduce that though. Only the placements specified are used?

**Comment by diondiondion** [comment] 2020-06-25 12:17
Good point, in the Codesandbox example, "top-start" is defined in `allowedAutoPlacements` which is why the menu is attached at the top. If you replace it with "bottom-end", it works as expected.

**Comment by atomiks** [comment] 2020-06-27 01:40
@FezVrasta this can be closed as this behavior is expected

**Closed** 2020-06-27 09:16 UTC
Labels: # BUG 🐞, NEEDS: triage
