### ISSUE TITLE
Example code no spacing between element and arrow

### ISSUE THREAD

**Issue by yooouuri** [popperjs/popper-core#1344] opened 2021-08-18 18:30 UTC
### CodeSandbox demo

https://jsfiddle.net/m5en4kvq/

### Steps to reproduce the problem

1. Copy the full code from the example (https://popper.js.org/docs/v2/tutorial/#full-code)
2. Run it

### What is the expected behavior?

There is a spacing between the tip of the arrow and the button.

### What went wrong?

There is no spacing between the tip of the arrow, the example shows a spacing between.

(jsfiddle)
![image](https://user-images.githubusercontent.com/12934957/129952415-d54287ed-dd03-4dd7-8bcc-69c4cc268461.png)

(screenshot from the example page)
![image](https://user-images.githubusercontent.com/12934957/129952461-07339212-874c-4d73-a82e-8c48184658d8.png)

**Comment by FezVrasta** [comment] 2021-08-18 18:41
Good catch, the `show` function should make sure to set the offset modifier again.

**Comment by FezVrasta** [comment] 2021-08-19 08:55
Dupe of https://github.com/popperjs/popper-core/issues/1271

Anyways I think I'll add a setter function support to the setOptions method:

```
setOptions(oldOptions => newOptions)
```

This should simplify everything

**Closed** 2021-08-19 08:55 UTC
Labels: # BUG 🐞, TARGETS: docs
