### ISSUE TITLE
Popper out of boundary

### ISSUE THREAD

**Issue by ar53n** [popperjs/popper-core#1037] opened 2020-03-23 15:56 UTC
Hello, thank you for the incredible library. But I have one problem with slider and absolute positioning in a slide.

### CodePen demo

https://codesandbox.io/s/crazy-jones-bj1vx?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce the problem

1. Create a slider with a big width and each slide has 100% width
2. Create an element near the left or right border
3. Begin start slider with another slide

### What is the expected behavior?

I want my tooltip to be higher than the button and centered if there is enough space. But if the button is too close to the edge of the slide, then position it by `mainAxis`.

### What went wrong?

My tooltip crawls beyond the boundary. But if begin slides from 1, then we show correct positioning

### Any other comments?

Maybe it's correct working. Are there any tips with which you can achieve this effect.  I want to help than I can.

**Comment by FezVrasta** [comment] 2020-03-23 16:22
Hey, I don't think I understand what's the issue, may you record a short clip to help me understand? You can record Gifs with https://getkap.co/

**Comment by ar53n** [comment] 2020-03-23 16:53
![example](https://user-images.githubusercontent.com/7085102/77341264-85993900-6d3f-11ea-8263-a45f328601a9.gif)
@FezVrasta how you can see after first reloading we can see the tooltip has correct positioning, but later when we move to the next slide and reload the page tooltip positioning out of the boundary. I set the boundary slide element.

**Comment by FezVrasta** [comment] 2020-03-23 16:58
Thanks for the clip, but that's not what I see in your sandbox. 

Probably you should hide the tooltips when the slide is not the active one, that should help with this situation.

I think the issue is that the non-active slide is reporting some weird values to Popper, because it's not being fully rendered.

**Comment by ar53n** [comment] 2020-03-23 17:42
I thought it was possible to limit the location of the popper within the boundary.

**Comment by FezVrasta** [comment] 2020-03-23 19:04
It is, but I think the out-of-view slide is being rendered in a weird way, making its size smaller than once it gets rendered completely, and this causes those issues.

**Comment by atomiks** [comment] 2020-03-24 00:32
It's because there are no events firing (and therefore Popper isn't updating the position) while it's being dragged/animated. You can use the `sticky` plugin to fix the issue.

**Comment by atomiks** [comment] 2020-03-24 00:41
> I thought it was possible to limit the location of the popper within the boundary.

You need to set `preventOverflow#tether` option to false

**Comment by ar53n** [comment] 2020-03-26 09:23
@atomiks 

> You need to set preventOverflow#tether option to false

Thanks for your advice, but it works not correctly. you can see the behavior of the popper when the tether is disabled in the slider.
You can set initialSlide value to 1 and reload. And then we can see the correct behavior
https://codesandbox.io/s/dawn-sea-5ecmf

**Comment by atomiks** [comment] 2020-03-26 10:13
I'm not really sure what you're trying to achieve. Maybe the sticky plugin? https://codesandbox.io/s/lucid-thompson-fjtkw

**Comment by FezVrasta** [comment] 2020-03-27 17:16
I'm going to close this because it looks like the issue is related to some 3rd party code, if you are able to reproduce this without any external libraries please post a repro here and I'll reopen the issue.

**Closed by FezVrasta** 2020-03-27 17:16 UTC
Labels: # BUG 🐞, NEEDS: triage
