### ISSUE TITLE
strategy: fixed is broken if its parent has will-change

### ISSUE THREAD

**Issue by layershifter** [popperjs/popper-core#1035] opened 2020-03-23 13:51 UTC
### CodeSandbox

https://codesandbox.io/s/misty-resonance-n18pt

### Steps to reproduce the problem

1. Open CodeSandbox
2. A tooltip is positioned inside container

![image](https://user-images.githubusercontent.com/14183168/77322848-a5ffce00-6d14-11ea-805a-1d3dd525e88f.png)

### What is the expected behavior?

The same positioning as without `will-change`.

### What went wrong?

Disabling of `gpuAcceleration` will not work 😭 
Any ideas why it happens? How it can be fixed?

**Comment by FezVrasta** [comment] 2020-03-23 14:16
Thanks for the report! Most likely the logic we use to detect offset parents is not taking in account the new render context generated by the `will-change: transform` property.

https://github.com/popperjs/popper-core/blob/master/src/dom-utils/getOffsetParent.js

**Comment by atomiks** [comment] 2020-03-24 00:47
Maybe this code as well, since it only affects the`fixed` strategy (and scrolling is not correct)? 

https://github.com/popperjs/popper-core/blob/be548db65912e1126581a44faa7f758ff004680a/src/dom-utils/getCompositeRect.js#L23-L35

**Comment by atomiks** [comment] 2020-03-24 01:02
It seems like the `offsetParent` is always `null` for `fixed` elements, but in this case, the `will-change` property (or `perspective` etc. properties as well) makes it an `offsetParent`? Is it a browser bug?

@FezVrasta it reminds me of these tweets you made: https://twitter.com/FezVrasta/status/1197515785289252864

**Comment by layershifter** [comment] 2020-03-24 08:34
As I understand this is related: https://bugs.chromium.org/p/chromium/issues/detail?id=20574&desc=2

This is very optimistic:
![image](https://user-images.githubusercontent.com/14183168/77404623-4ce67780-6db2-11ea-94ac-b7f2b4efc90d.png)

It looks that `transform` also affects it.


### without
![image](https://user-images.githubusercontent.com/14183168/77404757-7f907000-6db2-11ea-87ee-d754184cf912.png)

### `transform: translateZ(0);`

![image](https://user-images.githubusercontent.com/14183168/77404813-8fa84f80-6db2-11ea-95b1-5d04387c41eb.png)

**Comment by atomiks** [comment] 2020-03-24 08:49
Since it's a browser bug, I guess the only solution is to move the popper outside of the container element.

**Comment by layershifter** [comment] 2020-03-24 08:57
But, it means that all positioned elements should be rendered in `document.body` to safely avoid container issues. If so, it will be an accessibility issue in half cases, for example `MenuButton`:

https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html

```html
<div class="menu_button">
  <button aria-haspopup="true" aria-expanded="false" aria-controls="menu1">
    Actions
  </button>

  <ul
    <!-- should use Popper -->
    role="menu"
    style="display: none; position: absolute; top: 23.75px; left: 0px;"
  >
    <li role="menuitem">
      Action 1
    </li>
    <li role="menuitem">
      Action 2
    </li>
  </ul>
</div>
```

**Comment by atomiks** [comment] 2020-03-24 09:01
Why not:
1. Don't use `"fixed"` strategy unless the reference element is actually fixed
2. Don't use those properties, or if it's absolutely required, only append it outside as an escape hatch with a focus management solution in those cases

**Comment by layershifter** [comment] 2020-03-24 09:06
@atomiks thank you for participating in this discussion, really appreciate 👍 

> Don't use "fixed" strategy unless the reference element is actually fixed

Do you have any suggestions how I can avoid `strategy: fixed` (i.e. `position: fixed`) in this example?

![image](https://user-images.githubusercontent.com/14183168/77407839-13fcd180-6db7-11ea-996c-fb7ed62d9df1.png)

https://fluentsite.z22.web.core.windows.net/components/chat/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#usage-in-scrollable

**Comment by atomiks** [comment] 2020-03-24 09:21
The `flip` modifier is meant to solve that issue when it encounters a clipping boundary. Is there a problem with letting it flip to the bottom in that case to avoid getting clipped?

**Comment by layershifter** [comment] 2020-03-24 11:01
> Is there a problem with letting it flip to the bottom in that case to avoid getting clipped?

Yep, design requirement 😨
In our case it's not really clipping boundary and it should not flip to bottom ever.

See this screenshot as an example:
![image](https://user-images.githubusercontent.com/14183168/77418169-cee09b80-6dc6-11ea-914c-1e8d1aa3b901.png)

Elements that use `Popper` should be positioned inside whole viewport.

**Comment by atomiks** [comment] 2020-03-24 13:06
As long as you don't have `position: relative` on the container or parents of the popper, it won't be clipped inside a scrollable container. When you put `position` on a parent, it creates a clipping context and you need to move the popper out of the DOM hierarchy or use `fixed` (but there's a browser/spec bug with it as evidenced by that report). In this case your only solution is to move it outside and manage focus manually.

**Comment by FezVrasta** [comment] 2020-03-27 17:19
Should the issue be closed since it's actually a browser bug, or can we do something to mitigate or workaround the issue?

**Comment by atomiks** [comment] 2020-04-03 02:38
To summarize, the browser reports `fixedElement.offsetParent === null`, even in this case where a `transform/perspective/will-change` container actually becomes an offsetParent of the fixed element according to the spec. 

I think this means the only way to detect the actual offsetParent would be to either (unless there is a different technique):

- Allow the user to manually specify an `offsetParent` in this edge case (bad ergonomics)
- Traverse all ancestors to check for those properties (bad for performance)

Both aren't good so I think the only reasonable solution is for the user to change their DOM structure to workaround the issue...

**Comment by FezVrasta** [comment] 2020-04-03 05:13
Isn’t enough for the user to set a position: relative to the bugged offset parent? That should fix the detection and not affect the layout

**Comment by atomiks** [comment] 2020-04-03 12:47
No, as fixed elements don't have an `offsetParent` (always `null` even with `relative` property), but `will-change` creates one that the browser doesn't report

**Comment by FezVrasta** [comment] 2020-04-03 13:01
Ok then I can't think of anything we could do to address this problem, I'd say we can close this.

**Closed by FezVrasta** 2020-04-03 13:01 UTC
Labels: # BUG 🐞, DIFFICULTY: low, PRIORITY: medium, TARGETS: core

**Comment by FezVrasta** [comment] 2020-05-25 08:56
@atomiks I noticed that Firefox correctly reports the "transform parent" when you read `popperElement.offsetParent`. Do you think we could fix this bug at least on Firefox?

**Comment by wszydlak** [comment] 2020-05-25 09:21
According to #1111:

![image](https://user-images.githubusercontent.com/6583977/82797917-11326180-9e78-11ea-9716-84836e358efd.png)

![image](https://user-images.githubusercontent.com/6583977/82797967-27d8b880-9e78-11ea-8b82-2668fa380d86.png)

Which means:

For element with `position: fixed` containing block may be nearest element that has eg. `transform: translate(0)` (according to point 4). Also according to point 4. - offsetParent is not always the same as containing block.

Maybe you should consider something what [mezr](https://github.com/niklasramo/mezr#containingblock) library can do:

https://github.com/bpceee/bpceee.github.io/issues/10

**Comment by FezVrasta** [comment] 2020-05-25 09:35
The problem is that only Firefox reports the correct `offsetParent`, and doing as mezr does is going to kill performance.

**Comment by FezVrasta** [comment] 2020-05-25 09:59
I opened an issue on the Chromium bug tracker

https://bugs.chromium.org/p/chromium/issues/detail?id=1086125

**Comment by wszydlak** [comment] 2020-05-25 10:24
Strategy fixed also is not working properly in FF:

https://codesandbox.io/embed/dazzling-leftpad-cszp1?fontsize=14&hidenavigation=1&theme=dark

Also in FF `offsetParent` for `fixed` element inside `transformed` element will be not transformed element, but `body`:

![image](https://user-images.githubusercontent.com/6583977/82804349-683d3400-9e82-11ea-970b-2c45bf6ed8b7.png)

![image](https://user-images.githubusercontent.com/6583977/82804396-830fa880-9e82-11ea-9cc7-7108572c23a0.png)

This means that there is also something wrong with popper. Also I'm not sure if reported by you bug in chromium is correct, cause you need `offsetParent` to be `containing block` but this is not always true.

**Comment by FezVrasta** [comment] 2020-05-25 14:20
In my test case, Firefox reports the correct parent.

https://codepen.io/FezVrasta/pen/dyYLXLZ

**Comment by wszydlak** [comment] 2020-05-25 14:56
So why example https://codesandbox.io/embed/dazzling-leftpad-cszp1?fontsize=14&hidenavigation=1&theme=dark is not working properly? What's wrong with the example?

**Comment by FezVrasta** [comment] 2020-05-25 15:05
In Popper we manually handle the `position: fixed` case and we always return `null` to make the behavior consistent across browsers and fix some problems that otherwise arise.

**Comment by wszydlak** [comment] 2020-05-26 07:06
So if you manually broke behaviour to make it consistent across browsers, then I think you should at least add option for user to calculate containing block on popper side. This don't need to be default "on", but if somebody needs better behaviour in strategy fixed then should be able to do this. As i described - either option "on"/"off" for containing block calculation or some getter function which can be modified by developers who use popper.

Please consider this, as for now in our use cases popper@1 behavior is better at this time.
Also due to regression in popper@2 in this behaviour - popper@1 should not be marked as deprecated in npm registry.

**Comment by FezVrasta** [comment] 2020-05-26 13:21
From our tests, even popper@1 is broken for this use case.

**Comment by wszydlak** [comment] 2020-05-28 09:49
No, it is not broken:

Again: https://codesandbox.io/s/dazzling-leftpad-cszp1?fontsize=14&hidenavigation=1&theme=dark

Popper 1:
![image](https://user-images.githubusercontent.com/6583977/83126487-278b2800-a0d9-11ea-9db2-83e9d405eed5.png)

Popper 2:
![image](https://user-images.githubusercontent.com/6583977/83126529-3a056180-a0d9-11ea-8a97-0e3cdad4455d.png)


Probably it works better for popper@1 because of this function: https://github.com/popperjs/popper-core/blob/v1.x/packages/popper/src/utils/getFixedPositionOffsetParent.js

Why it has been removed in popper@2 and why there are no option to calculate parent on developer side?

**Comment by wszydlak** [comment] 2020-05-28 09:51
And also please reopen this issue due to bug which is still in popper@2, you closed issue but you shouldn't due to not working popper@2

**Comment by FezVrasta** [comment] 2020-05-28 10:56
Your tone is over the top, let's close this here.
