### ISSUE TITLE
Misaligned popper position

### ISSUE THREAD

**Issue by mkrds** [popperjs/popper-core#1223] opened 2021-01-25 14:27 UTC
### CodeSandbox demo

https://codesandbox.io/s/magical-kowalevski-4b9nw?file=/src/Popover.js

### Steps to reproduce the problem

Check the provided codesandbox and play around with window width as this bug is not always visible
### What is the expected behavior?

I'd expect the right border of both the reference element and popper element to be perflectly aligned.

### What went wrong?

There is a slight 1px misalignment.

<img width="605" alt="Zrzut ekranu 2021-01-25 o 14 37 58" src="https://user-images.githubusercontent.com/20651022/105717552-9054c980-5f20-11eb-8f32-a0cdc0616f1d.png">

### Any other comments?

I noticed that this bug occurs when both the `x` position and `width` of the reference element are decimals.

It looks like Popper incorrectly calculates the position of the element.

I've added `logger` modifier so that you can check console in the codesandbox to see and compare the resulting value provided by `Popperjs` and the one provided by me (which seems to be correct).

I also played around with `roundOffsets`, `gpuAcceleration` and nothing seems to fix this issue.

I'd consider this issue a high priority as it basically defeats the purpose of using this otherwise very useful library. 

I'm happy to help with fixing this issue if someone would provide me with some guidance :)

**Comment by FezVrasta** [comment] 2021-01-25 14:48
Have you tried to disable the `roundOffsets` option?

https://popper.js.org/docs/v2/modifiers/compute-styles/#options

**Comment by mkrds** [comment] 2021-01-25 14:58
@FezVrasta It's already disabled in the provided sandbox :)

**Comment by FezVrasta** [comment] 2021-02-16 15:45
You can now tweak the [`roundoffsets`](https://popper.js.org/docs/v2/modifiers/compute-styles/#roundoffsets) option to address these edge cases.

**Comment by mkrds** [comment] 2021-02-25 13:07
Hey @FezVrasta thanks for the reply, but I'm afraid that possibility to tweak the roundOffsets does not really help in this case as the `x` value passed to that `roundOffset` function is still incorrect.

**Comment by FezVrasta** [comment] 2021-02-25 13:58
Oh I see, you are right.

It seems to fix itself if you resize vertically, so it's more some timing issue than a wrong computation of the offsets.

**Comment by FezVrasta** [comment] 2021-02-25 13:59
Oh wait, sorry, I didn't read your code. You are using `useLayoutEffect` to generate a new popper each time, so the issue must be in the moment React calls your code. This is not really something Popper can address, you should make React play nicely with it tweaking your code.

Sorry for the churn. Closing.

**Comment by atomiks** [comment] 2021-02-25 14:22
@FezVrasta the issue is the popper's rect (width/height) is done with layout, while the reference is done with `getBoundingClientRect()`. In the CodeSandbox you can see the layout is `110` but the client one is `109.5xxx`, which looks to be causing the issue.  We use layout because of issues with transforms IIRC.

**Comment by FezVrasta** [comment] 2021-02-25 15:30
@atomiks Popper properly computes it if you vertically resize the window when the issue is present, so I'm positive is not a positioning bug.

**Comment by mkrds** [comment] 2021-02-25 15:57
@FezVrasta Changing the `useLayoutEffect` to `useEffect` does not change anything (apart from adding another issue of `flash of unpositioned element` ;) )

**Comment by FezVrasta** [comment] 2021-02-25 16:30
Ok nevermind, looked again, Popper bug, lol

**Comment by atomiks** [comment] 2021-02-26 00:36
I think we can use the client rect if it's within 0.5px of the layout one, otherwise, we don't use it (due the transforms issue).

**Closed** 2021-02-26 17:37 UTC
Labels: # BUG 🐞, DIFFICULTY: medium, PRIORITY: medium

**Comment by mkrds** [comment] 2021-03-01 12:53
@FezVrasta @atomiks sorry for the late reply, but unfortunately it looks like your PR does not 100% fix the issue. Take a look at the videos:


https://user-images.githubusercontent.com/20651022/109499396-238b9c80-7a95-11eb-8766-e5636c11f648.mov


https://user-images.githubusercontent.com/20651022/109499401-25556000-7a95-11eb-9e57-799722e5af05.mov

As you can see the right side border of the popper element is changing position while I'm scrolling, it occurs both in the provided codesandbox (although same as previously you have to play with screen width, as it does not occur all the time) and other project where I'm using popper.
