### ISSUE TITLE
wrong calculation when popper is appended to body and documentElement.clientHeight isn't equal to viewport height

### ISSUE THREAD

**Issue by young122849** [popperjs/popper-core#1203] opened 2020-12-23 13:02 UTC
Hello, I want to know why popper-core uses documentElement.clientHeight to calculate Popper's translate3d value？In some case documentElement.clientHeight is not equal to window.innerHeight ， and then it will cause calculation errors and wrong position.

![Lark20201223210032](https://user-images.githubusercontent.com/13938315/102998375-04870080-4562-11eb-947d-4d586ba840ea.png)

**Comment by Wizard67** [comment] 2020-12-25 03:42
Thanks for the explanation!

I have been confused by the popperjs positioning error and have spent some time on it.

[Reproduction](https://codesandbox.io/s/objective-edison-jjznd?file=/index.html)  (It may be necessary to refresh codesandbox's browser, otherwise popperjs may not be initialized properly).

**Comment by FezVrasta** [comment] 2021-02-20 07:45
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Closed by FezVrasta** 2021-02-20 07:45 UTC
Labels: # BUG 🐞, NEEDS: triage

**Comment by takakobem** [comment] 2022-12-22 15:09
@FezVrasta @young122849 
I encountered the same issue when `<!DOCTYPE html>` is defined in html file.
You can see the behavior here
https://codesandbox.io/s/clientheight-visualviewport-height-without-doctype-html-vo29cm

This is quite an edge case but following patch solved the issue.
```diff
diff --git a/node_modules/@popperjs/core/lib/modifiers/computeStyles.js b/node_modules/@popperjs/core/lib/modifiers/computeStyles.js
index fb0b314..9108f58 100644
--- a/node_modules/@popperjs/core/lib/modifiers/computeStyles.js
+++ b/node_modules/@popperjs/core/lib/modifiers/computeStyles.js
@@ -65,9 +65,10 @@ export function mapToStyles(_ref2) {
     var offsetParent = getOffsetParent(popper);
     var heightProp = 'clientHeight';
     var widthProp = 'clientWidth';
+    var documentElement = getDocumentElement(popper);
 
     if (offsetParent === getWindow(popper)) {
-      offsetParent = getDocumentElement(popper);
+      offsetParent = documentElement;
 
       if (getComputedStyle(offsetParent).position !== 'static' && position === 'absolute') {
         heightProp = 'scrollHeight';
@@ -80,7 +81,7 @@ export function mapToStyles(_ref2) {
 
     if (placement === top || (placement === left || placement === right) && variation === end) {
       sideY = bottom;
-      var offsetY = isFixed && offsetParent === win && win.visualViewport ? win.visualViewport.height : // $FlowFixMe[prop-missing]
+      var offsetY = isFixed && (offsetParent === win || offsetParent === documentElement) && win.visualViewport ? win.visualViewport.height : // $FlowFixMe[prop-missing]
       offsetParent[heightProp];
       y -= offsetY - popperRect.height;
       y *= gpuAcceleration ? 1 : -1;
@@ -88,7 +89,7 @@ export function mapToStyles(_ref2) {
 
     if (placement === left || (placement === top || placement === bottom) && variation === end) {
       sideX = right;
-      var offsetX = isFixed && offsetParent === win && win.visualViewport ? win.visualViewport.width : // $FlowFixMe[prop-missing]
+      var offsetX = isFixed && (offsetParent === win || offsetParent === documentElement) && win.visualViewport ? win.visualViewport.width : // $FlowFixMe[prop-missing]
       offsetParent[widthProp];
       x -= offsetX - popperRect.width;
       x *= gpuAcceleration ? 1 : -1;

```

**Comment by atomiks** [comment] 2022-12-22 15:21
@takakobem can you submit a PR with that, assuming it doesn't also break documents _with_ a doctype declaration? This was broken since the beginning but would be nice to have working
